name: Deploy Zukini Infrastructure

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  terraform:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set up AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-west-2" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Import Existing Resources
        run: |
          terraform import aws_lb.zukini_alb arn:aws:elasticloadbalancing:us-west-2:060795900722:loadbalancer/app/zukini-alb/ea77344562d7692d
          terraform import aws_lb_target_group.zukini_target_group arn:aws:elasticloadbalancing:us-west-2:060795900722:targetgroup/zukini-tg/a680e7679f7cf523
          terraform import aws_db_instance.zukini_rds database-2
          terraform import aws_amplify_app.zukini_amplify d35bfbej5ol5tf
          terraform import aws_autoscaling_group.zukini_asg zukini-asg
          terraform import aws_lb_listener.zukini_https_listener arn:aws:elasticloadbalancing:us-west-2:060795900722:listener/app/zukini-alb/ea77344562d7692d/49cce9d796385b53
          terraform import aws_cloudwatch_log_group.zukini_api_logs /zukini/api/calls
          terraform import aws_iam_role.ec2_cloudwatch_role zukini-ec2-cloudwatch-role
          terraform import aws_iam_instance_profile.ec2_profile zukini-ec2-cloudwatch-profile


      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve


      - name: Refresh ASG Instances
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name zukini-asg \
            --preferences '{"MinHealthyPercentage": 50, "InstanceWarmup": 300}'

      

      
